# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Step 3: merge the scripted categories with the agent's judgement and render the report.

Readiness is counted, not judged: every `fail` category is one blocking
item, every `advisory` category one advisory item, and a category that did
not run at all counts as blocking — the report cannot claim readiness for a
check it never made. `ready` means no blocking and no advisory items;
`advisory-only` means advisory items only; anything else is `blocking`.
"""

from __future__ import annotations

from typing import Any

SECTIONS = (
    ("spdx_headers", "A — SPDX headers"),
    ("commit_shape", "B — Commit message shape"),
    ("placeholder_convention", "C — Placeholder convention"),
    ("contributing_conventions", "D — CONTRIBUTING conventions"),
    ("injection_guard", "E — Prompt-injection guard"),
)
FOOTER = (
    "*Pre-first-PR checklist generated by `pre-first-pr-check`. No state was changed.\n"
    "Address any blocking items before opening your PR. Advisory items are recommended\n"
    "but will not prevent the PR from being accepted.*"
)
STATUSES = ("pass", "fail", "advisory")


def merge(categories: dict[str, dict[str, Any]], judgement: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Fold the agent's B1 / B3 / D-wording / E findings into the scripted results."""
    merged = {k: dict(v) for k, v in categories.items()}

    def add(category: str, findings: list[dict[str, Any]], status: str) -> None:
        if not findings:
            return
        entry = merged.setdefault(category, {"status": "pass", "details": "", "locations": []})
        entry.setdefault("violations", [])
        entry["violations"] = [*entry.get("violations", []), *findings]
        entry["locations"] = sorted(
            {*entry.get("locations", []), *(f.get("location", "") for f in findings)} - {""}
        )
        if status == "fail" or entry["status"] == "fail":
            entry["status"] = "fail"
        elif entry["status"] == "pass":
            entry["status"] = "advisory"

    add("commit_shape", judgement.get("B1", []), "fail")
    add("commit_shape", judgement.get("B3", []), "fail")
    add("contributing_conventions", judgement.get("D", []), "fail")
    injection = judgement.get("E")
    if isinstance(injection, dict):
        status = injection.get("status", "pass")
        merged["injection_guard"] = {
            "status": status if status in STATUSES else "fail",
            "details": injection.get("details", ""),
            "locations": [injection["location"]] if injection.get("location") else [],
        }
    return merged


def readiness(categories: dict[str, dict[str, Any]]) -> dict[str, Any]:
    blocking = sum(
        1 for key, _ in SECTIONS if categories.get(key, {"status": "fail"}).get("status") == "fail"
    )
    advisory = sum(1 for key, _ in SECTIONS if categories.get(key, {}).get("status") == "advisory")
    signal = "blocking" if blocking else "advisory-only" if advisory else "ready"
    sentence = {
        "ready": "Ready to open — no blocking or advisory items.",
        "advisory-only": "Ready to open — only advisory items remain.",
        "blocking": "Not ready yet — fix the blocking items first.",
    }[signal]
    return {"signal": signal, "blocking": blocking, "advisory": advisory, "sentence": sentence}


def render(summary: dict[str, Any], categories: dict[str, dict[str, Any]]) -> str:
    ready = readiness(categories)
    lines = [
        "## Pre-first-PR checklist",
        "",
        f"**Base:** {summary['base']}",
        f"**Commits on branch:** {summary['commits']}",
        f"**Files changed:** {summary['files']} ({summary['added']} added, {summary['modified']} modified, "
        f"{summary['deleted']} deleted)",
        "",
        "---",
    ]
    for key, title in SECTIONS:
        entry = categories.get(key)
        lines += ["", f"### {title}", ""]
        if entry is None:
            lines.append("FAIL — this check did not run.")
            continue
        status = entry["status"].upper()
        lines.append(f"{status}" + (f" — {entry['details']}" if entry.get("details") else ""))
        for item in entry.get("violations", []) or entry.get("problems", []) or entry.get("occurrences", []):
            where = item.get("commit") or item.get("location") or item.get("path") or ""
            what = item.get("summary") or item.get("token") or ""
            lines.append(f"- **[{'FAIL' if entry['status'] == 'fail' else 'ADVISORY'}]** `{where}` — {what}")
        if entry.get("advisory") and entry["status"] != "fail":
            lines.append(f"- **[ADVISORY]** {entry['advisory']}")
    lines += [
        "",
        "---",
        "",
        "### Summary",
        "",
        ready["sentence"],
        "",
        f"**Blocking:** {ready['blocking']}  **Advisory:** {ready['advisory']}",
        "",
        "---",
        "",
        FOOTER,
    ]
    return "\n".join(lines) + "\n"
