#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Generate `.github/labeler.yml` from the tool READMEs' `**Capability:**` lines.

Every `tools/<name>/README.md` declares the tool capabilities it provides
(`contract:*` / `substrate:*`, see docs/labels-and-capabilities.md). The
`labeler` workflow applies those labels to a pull request that touches the
tool, so the README line is the single source of truth: a new tool, or a
changed capability, needs no hand-edit of the labeler config.

Files that live under a tool directory but belong to something else are
excluded: a skill's eval fixtures under `tools/skill-evals/evals/`, and the
spec-loop specs and sync marker under `tools/spec-loop/`.

Run as a prek hook. Rewrites the file in place and exits 1 if it changed
(re-stage and commit again); `--check` reports drift without writing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_RELPATH = Path(".github") / "labeler.yml"

_CAP_RE = re.compile(r"^\*\*Capability:\*\*[ \t]+(.+)$", re.MULTILINE)
_LABEL_RE = re.compile(r"^(contract|substrate):[a-z0-9-]+$")

# Paths under a tool directory that do not count as touching that tool.
EXCLUDES: dict[str, tuple[str, ...]] = {
    "skill-evals": ("evals/**",),
    "spec-loop": ("specs/**", ".last-sync"),
}

# A pull request that would gain more path-based labels than this is a
# cross-cutting sweep (licence headers, dependency bumps across every tool);
# the labeler then applies none and leaves the capability to the maintainer.
LABELS_LIMIT = 8

HEADER = """\
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# GENERATED by tools/dev/generate-labeler-config.py from the
# `**Capability:**` line of every tools/<name>/README.md. Do not edit by
# hand; change the README and let the prek hook regenerate this file.
---
"""


def load_capabilities(root: Path) -> dict[str, list[str]]:
    """Map each tool-capability label to the sorted tool directories declaring it."""
    by_label: dict[str, list[str]] = {}
    for readme in sorted((root / "tools").glob("*/README.md")):
        match = _CAP_RE.search(readme.read_text(encoding="utf-8"))
        if not match:
            continue
        for raw in match.group(1).split("+"):
            label = raw.strip().strip("`").strip()
            if _LABEL_RE.match(label):
                by_label.setdefault(label, []).append(readme.parent.name)
    return by_label


def render(by_label: dict[str, list[str]]) -> str:
    lines = [HEADER.rstrip("\n"), f"changed-files-labels-limit: {LABELS_LIMIT}", ""]
    for label in sorted(by_label):
        tools = by_label[label]
        plain = [t for t in tools if t not in EXCLUDES]
        lines += [f"{label}:", "  - any:"]
        if plain:
            lines += ["      - changed-files:", "          - any-glob-to-any-file:"]
            lines += [f"              - 'tools/{t}/**'" for t in plain]
        for tool in (t for t in tools if t in EXCLUDES):
            lines += ["      - changed-files:", "          - all-globs-to-any-file:"]
            lines.append(f"              - 'tools/{tool}/**'")
            lines += [f"              - '!tools/{tool}/{pattern}'" for pattern in EXCLUDES[tool]]
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift without rewriting the file")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    path = args.root / CONFIG_RELPATH
    expected = render(load_capabilities(args.root))
    current = path.read_text(encoding="utf-8") if path.is_file() else ""
    if current == expected:
        return 0
    rel = CONFIG_RELPATH.as_posix()
    if args.check:
        print(f"{rel} is out of date — run tools/dev/generate-labeler-config.py", file=sys.stderr)
        return 1
    path.write_text(expected, encoding="utf-8")
    print(f"regenerated {rel} — re-stage it and commit again", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
