#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Generate `.github/labeler.yml` from the repository's own declarations.

The `labeler` workflow applies these labels to a pull request from the files
it touches, so each label's source of truth stays where it is declared and a
new tool or skill needs no hand-edit of the labeler config:

- `contract:*` / `substrate:*` come from the `**Capability:**` line of every
  `tools/<name>/README.md`.
- `family:*` and `capability:*` come from each skill's `family:` and
  `capability:` frontmatter, applied to the skill's directory and to its eval
  suite under `tools/skill-evals/evals/` (found through the `skills/<name>`
  symlink that names it).
- The three non-skill families of docs/labels-and-capabilities.md map to their
  paths: `family:tools` (tools, and plugins that only package a tool),
  `family:ci` (`.github/`, the pre-commit config, `tools/dev/`, root tooling
  files such as `pyproject.toml` and `.gitignore`), `family:setup` (Magpie's
  own `.apache-magpie-overrides/` and pin) and
  `family:docs` (`docs/`, `MISSION.md`, every `README.md` and root `*.md`).
  A family's guide under `docs/<family>/` also gets that family.

Only labels the taxonomy doc defines are emitted, so a typo in frontmatter
cannot create a label. Files that live under a tool directory but belong to
something else are excluded from the tool labels: a skill's eval fixtures
under `tools/skill-evals/evals/`, and the spec-loop specs and sync marker
under `tools/spec-loop/`.

Run as a prek hook. Rewrites the file in place and exits 1 if it changed
(re-stage and commit again); `--check` reports drift without writing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_RELPATH = Path(".github") / "labeler.yml"

_CAP_RE = re.compile(r"^\*\*Capability:\*\*[ \t]+(.+)$", re.MULTILINE)
_LABEL_RE = re.compile(r"^(contract|substrate):[a-z0-9-]+$")

# Paths under a tool directory that do not count as touching that tool.
EXCLUDES: dict[str, tuple[str, ...]] = {
    "skill-evals": ("evals/**",),
    "spec-loop": ("specs/**", ".last-sync"),
}

# A pull request that would gain more path-based labels than this is a
# cross-cutting sweep (licence headers, dependency bumps across every tool);
# the labeler then applies none and leaves the capability to the maintainer.
# actions/labeler applies *no* changed-files label when more new ones match
# than this, so the limit is a cliff, not a cap. Keep it well above what a
# normal pull request touches (a family, a capability or two, a few tools).
LABELS_LIMIT = 20

TAXONOMY_RELPATH = Path("docs") / "labels-and-capabilities.md"
_TAXONOMY_RE = re.compile(r"^\| `((?:family|capability):[a-z0-9-]+)` \|", re.MULTILINE)

# The non-skill families and the paths they cover.
PATH_FAMILIES: dict[str, tuple[str, ...]] = {
    "family:ci": (
        ".github/**",
        ".pre-commit-config.yaml",
        "tools/dev/**",
        ".gitignore",
        ".gitattributes",
        "pyproject.toml",
        "uv.lock",
        ".typos.toml",
        ".rat-excludes",
        ".lychee.toml",
    ),
    # Magpie's own adoption of the framework: the committed overrides and pin.
    "family:setup": (".apache-magpie-overrides/**", ".apache-magpie.lock"),
    "family:docs": ("docs/**", "MISSION.md", "*.md", "**/README.md"),
}

HEADER = """\
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# GENERATED by tools/dev/generate-labeler-config.py from the
# `**Capability:**` line of every tools/<name>/README.md and the `family:` /
# `capability:` frontmatter of every skill. Do not edit by hand; change the
# README or the skill and let the prek hook regenerate this file.
---
"""


def load_capabilities(root: Path) -> dict[str, list[str]]:
    """Map each tool-capability label to the sorted tool directories declaring it."""
    by_label: dict[str, list[str]] = {}
    for readme in sorted((root / "tools").glob("*/README.md")):
        match = _CAP_RE.search(readme.read_text(encoding="utf-8"))
        if not match:
            continue
        for raw in match.group(1).split("+"):
            label = raw.strip().strip("`").strip()
            if _LABEL_RE.match(label):
                by_label.setdefault(label, []).append(readme.parent.name)
    return by_label


def taxonomy_labels(root: Path) -> set[str]:
    """The `family:*` and `capability:*` labels docs/labels-and-capabilities.md defines."""
    path = root / TAXONOMY_RELPATH
    return set(_TAXONOMY_RE.findall(path.read_text(encoding="utf-8"))) if path.is_file() else set()


def _frontmatter(skill_md: Path) -> dict[str, list[str]]:
    """`family` and `capability` from a SKILL.md frontmatter, as lists of values."""
    lines = skill_md.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    out: dict[str, list[str]] = {}
    key = None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        top = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if top:
            key, value = top.group(1), top.group(2).strip()
            if key in ("family", "capability") and value:
                out[key] = [value]
            elif key in ("family", "capability"):
                out[key] = []
            continue
        item = re.match(r"^\s+-\s+(.+)$", line)
        if item and key in ("family", "capability"):
            out[key].append(item.group(1).strip())
    return out


def load_path_rules(root: Path) -> dict[str, list[str]]:
    """Map each `family:*` / `capability:*` label to the sorted globs it covers."""
    known = taxonomy_labels(root)
    rules: dict[str, set[str]] = {}
    excluded: dict[str, tuple[str, ...]] = {}

    def add(label: str, *globs: str) -> None:
        if label in known:
            rules.setdefault(label, set()).update(globs)

    evals_for: dict[Path, str] = {}
    for link in sorted((root / "skills").glob("*")):
        if link.is_symlink():
            evals_for[link.resolve()] = link.name
    for skill_md in sorted((root / "plugins").glob("magpie-*/skills/*/SKILL.md")):
        skill_dir = skill_md.parent
        globs = [f"{skill_dir.relative_to(root).as_posix()}/**"]
        suite = evals_for.get(skill_dir.resolve())
        if suite and (root / "tools" / "skill-evals" / "evals" / suite).is_dir():
            globs.append(f"tools/skill-evals/evals/{suite}/**")
        meta = _frontmatter(skill_md)
        for family in meta.get("family", []):
            add(f"family:{family}", *globs)
        for capability in meta.get("capability", []):
            add(capability, *globs)
    for plugin in sorted((root / "plugins").glob("magpie-*")):
        if not plugin.is_dir():
            continue
        family = f"family:{plugin.name.removeprefix('magpie-')}"
        if (plugin / "skills").is_dir():
            add(family, f"plugins/{plugin.name}/**")
        else:  # a plugin that only packages a tool
            add("family:tools", f"plugins/{plugin.name}/**")
        if (root / "docs" / plugin.name.removeprefix("magpie-")).is_dir():
            add(family, f"docs/{plugin.name.removeprefix('magpie-')}/**")
    if (root / "tools").is_dir():
        add("family:tools", "tools/**")
        if "family:tools" in rules:  # skill evals and specs are not tool code
            excluded["family:tools"] = ("tools/skill-evals/evals/**", "tools/spec-loop/specs/**")
    for label, path_globs in PATH_FAMILIES.items():
        add(label, *path_globs)

    def prune(globs: set[str]) -> list[str]:
        """Drop a glob that a broader `<dir>/**` in the same rule already covers."""
        trees = [g[:-2] for g in globs if g.endswith("/**")]
        return sorted(g for g in globs if not any(g != t + "**" and g.startswith(t) for t in trees))

    out = {label: prune(globs) for label, globs in rules.items()}
    for label, negations in excluded.items():
        out[label] = out[label] + [f"!{glob}" for glob in negations]
    return out


def render(by_label: dict[str, list[str]], path_rules: dict[str, list[str]] | None = None) -> str:
    lines = [HEADER.rstrip("\n"), f"changed-files-labels-limit: {LABELS_LIMIT}", ""]
    for label in sorted(path_rules or {}):
        globs = (path_rules or {})[label]
        negations = [g for g in globs if g.startswith("!")]
        if not negations:
            lines += [f"{label}:", "  - changed-files:", "      - any-glob-to-any-file:"]
            lines += [f"          - '{glob}'" for glob in globs]
        else:
            # A negation only works inside all-globs-to-any-file, so the excluded
            # tree gets its own group, OR-ed with the plain globs.
            tree = "tools/**"
            plain = [g for g in globs if not g.startswith("!") and g != tree]
            lines += [f"{label}:", "  - any:"]
            if plain:
                lines += ["      - changed-files:", "          - any-glob-to-any-file:"]
                lines += [f"              - '{glob}'" for glob in plain]
            lines += [
                "      - changed-files:",
                "          - all-globs-to-any-file:",
                f"              - '{tree}'",
            ]
            lines += [f"              - '{glob}'" for glob in negations]
        lines.append("")
    for label in sorted(by_label):
        tools = by_label[label]
        plain = [t for t in tools if t not in EXCLUDES]
        lines += [f"{label}:", "  - any:"]
        if plain:
            lines += ["      - changed-files:", "          - any-glob-to-any-file:"]
            lines += [f"              - 'tools/{t}/**'" for t in plain]
        for tool in (t for t in tools if t in EXCLUDES):
            lines += ["      - changed-files:", "          - all-globs-to-any-file:"]
            lines.append(f"              - 'tools/{tool}/**'")
            lines += [f"              - '!tools/{tool}/{pattern}'" for pattern in EXCLUDES[tool]]
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift without rewriting the file")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    path = args.root / CONFIG_RELPATH
    expected = render(load_capabilities(args.root), load_path_rules(args.root))
    current = path.read_text(encoding="utf-8") if path.is_file() else ""
    if current == expected:
        return 0
    rel = CONFIG_RELPATH.as_posix()
    if args.check:
        print(f"{rel} is out of date — run tools/dev/generate-labeler-config.py", file=sys.stderr)
        return 1
    path.write_text(expected, encoding="utf-8")
    print(f"regenerated {rel} — re-stage it and commit again", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
